# Generated by Django 5.0.6 on 2024-05-23 06:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='uploadtime',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
