# Generated by Django 5.0.6 on 2024-05-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_records_uploadtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
