# Generated by Django 5.0.6 on 2024-05-25 10:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='health_records',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
